### ISSUE TITLE
Add styles only when values are present. 

### ISSUE THREAD

**Issue by Danishkhurshid** [Entermedia-LLC/nextjs-starter#19]
<img width="228" alt="Screenshot 2023-02-09 at 1 58 44 PM" src="https://user-images.githubusercontent.com/19993386/217758083-75523b10-0540-40c3-855b-cea8485be913.png">

Currently, styles getting added by generateStyles function inside functions/gutenberg/generateStyles are adding empty styles too. I think we need to fix this by conditionally adding the styles only when values are present.

**Comment by Danishkhurshid** [comment]
@bmarshall511 assigning this to you for review.

**Comment by bmarshall511** [comment]
@Danishkhurshid Yeah, I saw that the other day. Thanks for creating an issue for it!

**Comment by Danishkhurshid** [comment]
@bmarshall511 added a PR. Plz check.

**Comment by bmarshall511** [comment]
@Danishkhurshid Looks great, thanks @Danishkhurshid!
